### ISSUE TITLE
Need specific ARM device required?

### ISSUE THREAD

**Issue by ifshuaishuai** [ARM-software/HWCPipe#15]
I compiled and run on my android devices, got following error :(

> PMU profiler initialization failed: PMU counters not available.
> Mali profiler initialization failed: Failed to get HW info.

Does this library need run on specific arm device?

**Comment by AttilioProvenzano-ARM** [comment]
Hi :)

Regarding the PMU counters, it could be that your devices disable profiling by default.
You could try running:
`adb shell setprop security.perf_harden 0`

Regarding Mali counters, they should work with any device with a Mali GPU. Could you share the models of the devices you are using? So we can try to reproduce the issue internally.

**Comment by ifshuaishuai** [comment]
Thanks for the quick replay.
I Tried ARM mobile studio profiling today, and found out it works fine. so i will look into that, it must be my fault.
Thanks again.

**Comment by AttilioProvenzano-ARM** [comment]
Glad to hear Mobile Studio helped! :)
If you'd like to share which devices you were using it's still useful for us, so we can fix HWCPipe for those.

**Comment by ifshuaishuai** [comment]
Hi:
  My Android device runs on snapdragon 835, phone model is XiaoMi MiX2. :)

**Comment by AttilioProvenzano-ARM** [comment]
Hi, thanks for sharing the phone model! This helped us find a bug on Snapdragon devices, which we fixed in this PR: https://github.com/ARM-software/HWCPipe/pull/17

You should now be able to see CPU counters on Snapdragon. GPU counters are not supported unfortunately, HWCPipe only supports Mali GPUs at the moment.
