### ISSUE TITLE
Can we get HWCPipe counter as floating values above 3rd party games like PUBG and COD?

### ISSUE THREAD

**Issue by dubeyabhijeet** [ARM-software/HWCPipe#35]
Suppose i play PUBG game and want a HWCPipe app which runs on background and want to see how GPU/CPU counters vary with PUBG scenes or action. Is it possible to create a Android app for HWCPipe which shows counters as floating values above other apps. If yes then please guide how to integrate the app with HWCPipe?

**Comment by wasimabbas-arm** [comment]
I think there might be a way to create overlay android app but I think thats only possible for your own application not sure you can just use it on a separate application. Also the android security model won't let you access counters for other processes so this might not work. We haven't created any such apps or had this use case in mind.

**Comment by dubeyabhijeet** [comment]
So counters are specific to processes or generic too? Suppose i just want to see GPU/CPU counters while running other apps. If its not specific with PUBG [Suppose we are running PUBG] then also its fine. Is it possible?
