### ISSUE TITLE
How to implement MaliFragOverdraw?

### ISSUE THREAD

**Issue by ylz-at** [ARM-software/HWCPipe#39]
Fragments per pixel. This expression computes the number of fragments shaded per output pixel. High levels of overdraw can be a significant processing cost, especially when rendering to a high-resolution framebuffer. Note that this expression assumes a 16x16 tile size is used during shading. For render passes using more than 256 bits per pixel the tile size will be dynamically reduced and this assumption will be invalid.

**Comment by solidpixel** [comment]
Compute like this:

`(FRAG_WARPS * <warp width>) / (FRAG_PTILES * <tile size> * <tile size>)`

Will need to know the warp width and tile size for the GPU you are targeting.
