### ISSUE TITLE
Support Mali GPU Frequency and Usage counters

### ISSUE THREAD

**Issue by ylz-at** [ARM-software/HWCPipe#40]
Currently, I think it is not possible for Mali to get GPU Frequency by reading sysfs on Android 10+.
Could you please manage to expose these metrics?

The standardized path in Android for GPU Frequency is, `/sys/kernel/gpu/gpu_clock`.

These counters are very important for Game performance tuning.

**Comment by solidpixel** [comment]
We can't expose this, `/sys/` isn't a readable partition on Release builds of Android.
