### ISSUE TITLE
PMU counters not available

### ISSUE THREAD

**Issue by xiaochengyez** [ARM-software/HWCPipe#51]
12-15 18:04:32.028 24817 24817 V HWCPipe : perf_event_open failed. Counter ID: PERF_COUNT_HW_BRANCH_MISSES
12-15 18:04:32.028 24817 24817 V HWCPipe : perf_event_open failed. Counter ID: PERF_COUNT_HW_BRANCH_INSTRUCTIONS
12-15 18:04:32.028 24817 24817 V HWCPipe : perf_event_open failed. Counter ID: PERF_COUNT_HW_CACHE_MISSES
12-15 18:04:32.028 24817 24817 V HWCPipe : perf_event_open failed. Counter ID: PERF_COUNT_HW_CACHE_REFERENCES
12-15 18:04:32.028 24817 24817 V HWCPipe : perf_event_open failed. Counter ID: PERF_COUNT_HW_INSTRUCTIONS
12-15 18:04:32.028 24817 24817 V HWCPipe : perf_event_open failed. Counter ID: PERF_COUNT_HW_CPU_CYCLES
12-15 18:04:32.028 24817 24817 V HWCPipe : PMU profiler initialization failed: PMU counters not available.

**Comment by xiaochengyez** [comment]
My Android device runs on Dimensity 810, phone model is Redmi Note 11.

**Comment by solidpixel** [comment]
Did you run: 

`adb shell setprop security.perf_harden 0`

... to enable access to Perf?

**Comment by solidpixel** [comment]
Old question, closing.
