### ISSUE TITLE
Could not identify Mali-G52

### ISSUE THREAD

**Issue by Angiewei** [ARM-software/HWCPipe#54]
I use Huawei nova 6 se, Mali-G52, get an error "Could not identify GPU", try to print product_id is "b1a1545d".  is it not supported?

**Comment by solidpixel** [comment]
Thanks for the bug report - looks like support for G52 was never added. I'll get this done ASAP.

**Comment by solidpixel** [comment]
Should be fixed in 129348aafc1f056264bdca178696e02267c12094
