### ISSUE TITLE
MaliProfiler::init() exception: "Failed settings flags ioctl."  on Mali-G710

### ISSUE THREAD

**Issue by ming4883** [ARM-software/HWCPipe#57]
Hello, while testing the [main branch](https://github.com/ARM-software/HWCPipe/commit/fe9a05b6257d7c74119391c6ffa9c157989ff45f) on Dimensity 9000 SoC (Mali-G710). I received the "Failed settings flags ioctl." exception while invoking MaliProfiler::init() at [line 493](https://github.com/ARM-software/HWCPipe/blob/main/vendor/arm/mali/mali_profiler.cpp#L493)

I confirmed that `adb shell setprop security.perf_harden 0` is already set on the device.

**Comment by seldy** [comment]
This is because the API version wasn't set, you may copy the version set codes from get_mali_hw_info() and put it before the set flags.

**Comment by ming4883** [comment]
Great, it works!!

Shell I create a pull request on that?

**Comment by solidpixel** [comment]
The 2.0 release completely rewrites the library, with a new backend that should be more reliable. Please retry with that, and create a new issue if problems remain. 

Thanks, 
Pete
