### ISSUE TITLE
perf_event_open failed. Counter ID: PERF_COUNT_HW_CPU_CYCLES

### ISSUE THREAD

**Issue by PIKACHUIM** [ARM-software/HWCPipe#59]
Hello, when I use your code to compile and run on Android device, it prompts me:
```
perf_event_open failed. Counter ID: PERF_COUNT_HW_CPU_CYCLES
PMU profiler initialization failed: PMU counters not available.
```
How to solve this problem? Thank you very much!
My device is `Redmi Note 10 Pro (Mali GPU G77MC)`
I ensure that this command is executed successfully: 
`ADB shell setprop security perf_harden 0`
I want to know how to compile and run hwpipe correctly on Android devices.
 I downloaded Android NDK to my Linux system and specified the Android tool chain in cmake.
I don't know whether my compilation method is correct. Thank you very much!

More, I found about this issue:
in
```
 void PmuCounter::open(const perf_event_attr &perf_config)
_fd = syscall(__NR_perf_event_open, &perf_config, 0, -1, -1, 0);
```
the `_fd` = -1

**Comment by PIKACHUIM** [comment]
Also, this code can NOT be excuted:
```
    auto cpu_counters = h.cpu_profiler()->supported_counters();
    auto gpu_counters = h.gpu_profiler()->supported_counters();
```
It shows:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

**Comment by JakeDaynes** [comment]
Can confirm that on a Pixel 6 Pro I'm getting a segmentation fault when trying to execute 
`auto gpu_counters = h.gpu_profiler()->supported_counters();`

**Comment by solidpixel** [comment]
Thanks for the bug reports - I'll take a look.

**Comment by solidpixel** [comment]
The 2.0 release completely rewrites the library, with a new backend that should be more reliable. Please retry with that, and create a new issue if problems remain. 

Thanks, 
Pete
