### ISSUE TITLE
Support for hw_ver_ 4

### ISSUE THREAD

**Issue by msreekan** [ARM-software/HWCPipe#60]
I have a device with Mali T720 and this check fails!
```
if (hw_ver_ < 5)
	{
	    std::cout << __LINE__ << "/" << __func__ << " " << hw_ver_ << "\n" ;
		throw std::runtime_error("Unsupported HW version.");
	}
```
https://github.com/ARM-software/HWCPipe/blob/8cc02065b4ef249127aa0164dc0d62d65c0d4203/vendor/arm/mali/mali_profiler.cpp#L591 

Were we planning to add support for hw_ver < 5?

**Comment by solidpixel** [comment]
There is currently no plan to add support for Mali-T720.
