### ISSUE TITLE
No compatibility with panfrost/lima drivers in armbian?

### ISSUE THREAD

**Issue by sxz0** [ARM-software/HWCPipe#61]
Hi, 
I am using several Single Board Computers (RockPro64, Rock64, BananaPi), including Mali GPUs (400, T860). I am trying to use HWCPipe to access the GPU counters. However, the armbian version I am using does not show the "/dev/mali0" or "/dev/mali" devices. Instead, it shows "/dev/dri/card0 and 1".

I have tried to modify "./vendor/arm/mali/mali_profiler.h" with the other GPU directory but HWCPipe is not able to use it. It returns:
_HWCPipe [INFO] : Mali profiler initialization failed: Failed to check version._

Does anyone have some idea of how I could use HWCPipe in armbian? I have also tried to install the "mali" kernel module but without success so far.

**Comment by solidpixel** [comment]
This project was designed for the Arm commercial drivers, so assumes the kernel IOCTL interface for the commercial kernel driver. 

I'm not sure if Panfrost has the same mechanism for counter sampling (if it does we'd be happy to accept PRs to support it, BUT beware that the current version of HWCPipe is likely to change considerably, so if anyone wants to pick this up please let me know first so we can coordinate).

**Comment by solidpixel** [comment]
Closing, as this is out of scope for the time being.
