### ISSUE TITLE
MaliProfiler::init() exception: "Failed settings hwcnt reader ioctl." on Mali-G77

### ISSUE THREAD

**Issue by bambloo** [ARM-software/HWCPipe#62]
I got this exception with errno 12...

**Comment by bengaineyarm** [comment]
Hi @bambloo 

What version of Streamline / gator were you using?

Is the issue reproducible after device reboot?

**Comment by bengaineyarm** [comment]
Any additional information you can provide?

What target is it?

Does the issue reproduce consistently? If you reboot the device, does it still occur?

**Comment by bambloo** [comment]
I just want to sample GPU Counters for testing usage.
The issue occured occasionally no matter I reboot the device or not.
On some device on which this issue occurs almost every time, I can run the code correctly after I reboot the device, but fail occurs after a while.

I changed the buffer_count_ value to less than 16, as a result, mapping error happened.
It may be caused by the dma memory the mali gpu driver using, for errno 12 means Out of memory...

**Comment by solidpixel** [comment]
The 2.0 release completely rewrites the library, with a new backend that should be more reliable. Please retry with that, and create a new issue if problems remain. 

Thanks, 
Pete
