### ISSUE TITLE
Could I get total cycles of gpu?

### ISSUE THREAD

**Issue by vkensou** [ARM-software/HWCPipe#63]
I want get total cycles of gpu, so I can calculate gpu's usage/utilization = gpu_active_cycles/total_cycles. 
Or maybe I'm wrong, Please tell me how to obtain GPU usage/utilization information.

**Comment by solidpixel** [comment]
You can't, at least not from HWCPipe by itself. 

You can measure the GPU active cycles between two points, but the library has no way of knowing what the GPU frequency is, as that is handled by the platform hardware outside of the GPU itself.
