### ISSUE TITLE
Identify big.LITTLE clusters?

### ISSUE THREAD

**Issue by darksylinc** [ARM-software/HWCPipe#66]
Hi!

From this project, [libGPUInfo](https://github.com/ARM-software/libGPUInfo) was created and we are very thankful for that!

But we've hit another problem: Identifying big.LITTLE systems on Android.

More specifically we need to estimate how many threads we should create and leave out the little cores (for two reasons: a. [bugs](https://www.yosoygames.com.ar/wp/2023/07/samsung-galaxy-a54-gaming-performance-what-the-heck-is-going-on/) and b. algorithms that assume all cores takes more or less the same time).

Of course on Android we (unfortunately) cannot set the thread affinity to a CPU core, thus knowing this information is half the battle; _we can only hope_ that if we create 4 threads on a 4+4 system, the 4 threads will be scheduled on the 4 big cpus (or the 4 little ones). But we can be certain that by creating 8 threads, we will always be limited by the little cores\*.

\* Ultimately we expose the setting to the user to allow an override on the number of CPU cores to use. However it's nice to autodetect an ideal number that works best out of the box for most systems.

Thus what we'd need is something like this:

```cpp
struct CpuCluster
{
	uint32_t numCores;
        // The range is in range [0; num_clusters)
        // Where 0 is slowest cluster, and num_clusters - 1 the fastest cluster
	uint32_t perfMetric; 
};

std::vector<CpuCluster> getClusterConfig();
```

So far looking in all of https://github.com/ARM-software I can see that ARM itself parses the output of `/proc/cpuinfo` and match the CPU info model names with known model names if big cores ('A15', 'A57', 'A72', 'A73'). That is:

1. Not future proof.
2. Doesn't work on Android (cpuinfo on android returns "ARMv8 Processor rev 0 (v8l)" for one cluster and "ARMv8 Processor rev 1 (v8l)" for the other cluster.

Another solution is to parse cpuinfo and identify different model/revision/etc as different clusters. However for example the [POCO F2 Pro](https://www.gsmarena.com/xiaomi_poco_f2_pro-10220.php) contains 3 clusters, but following this method only 2 clusters are identified because the 2 Mid and the 1 High core are all the same A77 CPU running at different speeds. [CPU-Z](https://play.google.com/store/apps/details?id=com.cpuid.cpu_z) runs into this issue.

So far what we're doing is parsing the output of `/sys/devices/system/cpu/cpu*/cpufreq/scaling_available_frequencies` and grouping CPUs with the same set.

Then sorting them by `/sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq`. If 2 clusters have the same max freq, then assumes lower CPU idx is little, higher is big core. It's not fully reliable because it assumes:

1. Clusters don't have the same scaling_available_frequencies
2. Their max frequency determines their performance
3. Their CPU order is relevant

It would be nice if ARM had an official ABI on Android so that his information can be fetched reliably and be future proof. [Intel has such library](https://github.com/GameTechDev/HybridDetect).

Cheers

**Comment by solidpixel** [comment]
Thanks for the request. It's not something we'd be willing to put in to this project, as this one is explicitly targeting the Arm GPU counters, but I could imagine this as another sibling project (libCPUInfo perhaps).

I'll raise the request internally. 

Cheers, 
Pete

**Comment by darksylinc** [comment]
Thanks!

Btw I was proven wrong on this bit:

> Of course on Android we (unfortunately) cannot set the thread affinity to a CPU core, thus knowing this information is half the battle

We CAN successfully set thread affinity (some implementation details apply, namely I've been told Android likes to periodically "forget" the thread affinities so they need to be re applied; we haven't experienced this phenomena ourselves though) which makes this functionality way more relevant.
