### ISSUE TITLE
Mali-G715 is not surport

### ISSUE THREAD

**Issue by wleebo** [ARM-software/HWCPipe#70]
Mali-G715-Immortalis is not surport

**Comment by bengaineyarm** [comment]
Hi @wleebo can you tell me what version you are using? The old v1 interface certainly does not support G715, but the current v2 interface should.
What specific issue are you seeing?

**Comment by wleebo** [comment]
I try to run the sample Surface Rotation in the Vulkan_Sample, but it can't get the count of "External Read Stalls"!
