### ISSUE TITLE
Android graphics mem drops when HWCPipe is enabled

### ISSUE THREAD

**Issue by Hy9996** [ARM-software/HWCPipe#74]
Hi there, we are using HwcPipe analyzing GPU performance of our game, and we found that on the MTK 9200 chip, a sudden GPU memory drop occurs after calling start_sampling(). This issue was not observed on other platforms, including the MTK 9300. 

![image](https://github.com/ARM-software/HWCPipe/assets/160709706/fa2b109d-3d5f-4f6f-a5d3-07ba79f7ed51)

Our device: Vivo X90

**Comment by solidpixel** [comment]
What tool is this measured with? The Android Studio memory profiler?

**Comment by Hy9996** [comment]
Yes, the picture posted above is from Android Studio, we also tried to collect the memory data directly from the java api("summary.graphics" in Debug.MemoryInfo), but shows the same result.

**Comment by solidpixel** [comment]
Thanks for confirming - I'll see if the GPU driver team have any ideas that can explain this one.

**Comment by solidpixel** [comment]
Closing - old issue, we could not explain or reproduce on our devices.
