### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by jsemeda** [ARM-software/HWCPipe#76]
I am running on Windows10, MSVC 2022
I downloaded and built the cmakelists file and it generated a hwcpipe.sln for MSVC. The solution has 2 projects, device and hwcpipe, when building the solution I am getting 228 errors. This seems to be a Linux project as it is asking for Linux include files. Can this library be built for Windows10?

**Comment by markbarnett-arm** [comment]
Hi @jsmedia. HWCPipe is designed for use with the commercial Mali driver for Linux/Android. Building for a Linux or Android target requires a clang- or gcc-based toolchain and a relevant sysroot (e.g. as provided by the Android NDK). Windows targets are not supported.
