### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by s-moraes** [ARM-software/HWCPipe#8]
Hi,
  There will be any release version? Should we consider the current source code as stable?

Thank you,
Saulo

**Comment by wasimabbas-arm** [comment]
We are in the middle of a big refactor and should be pushing that soon to v1.0 but the current master should be stable enough too. If you find issues please let us know.

**Comment by saulomoraes** [comment]
@wasimabbas-arm,

  thanks for your reply.

  My need for release version is basically to have a "compressed" (zip, tar.gz ....) file at github's Release tab (similar to ARMNN). It is usefull when users need to integrate automated build scripts (with no need to use git commands).

  Hope you are considering this approach.


thx,
Saulo

**Comment by wasimabbas-arm** [comment]
That should be possible once we have a solid version we can release.

**Comment by wasimabbas-arm** [comment]
We have now release v1.0.0
