### ISSUE TITLE
Use of "std::vector" with "const std::pair"

### ISSUE THREAD

**Issue by s-moraes** [ARM-software/HWCPipe#9]
I am trying to compile with gnu g++ 6.2.1 (armv7l), to test HWCPipe in a non-Android platform.

and a small modification were necessary:
**mali_counter.h:**
65: -       const std::vector<**const std::pair**<const char *, const char *>> _jm_counter_names {
65: +       const std::vector<std::pair<const char *, const char *>> _jm_counter_names {
69: -       const std::vector<**const std::pair**<const char *, const char *>> _mmu_counter_names  {
69: +       const std::vector<std::pair<const char *, const char *>> _mmu_counter_names  {

**Because of error:**
[    8s]                  from /home/abuild/rpmbuild/BUILD/HWCPipe-0.0.1/src/mali_counter.cpp:24:
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_construct.h: In instantiation of 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = const std::pair<const char*, const char*>; _Args = {const std::pair<const char*, const char*>&}]':
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_uninitialized.h:75:18:   required from 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const std::pair<const char*, const char*>*; _ForwardIterator = const std::pair<const char*, const char*>*; bool _TrivialValueTypes = false]'
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_uninitialized.h:126:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const std::pair<const char*, const char*>*; _ForwardIterator = const std::pair<const char*, const char*>*]'
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_uninitialized.h:281:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = const std::pair<const char*, const char*>*; _ForwardIterator = const std::pair<const char*, const char*>*; _Tp = const std::pair<const char*, const char*>]'
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_vector.h:1288:33:   required from 'void std::vector<_Tp, _Alloc>::_M_range_initialize(_ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = const std::pair<const char*, const char*>*; _Tp = const std::pair<const char*, const char*>; _Alloc = std::allocator<const std::pair<const char*, const char*> >]'
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_vector.h:379:2:   required from 'std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = const std::pair<const char*, const char*>; _Alloc = std::allocator<const std::pair<const char*, const char*> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<const std::pair<const char*, const char*> >]'
[    8s] /home/abuild/rpmbuild/BUILD/HWCPipe-0.0.1/src/mali_counter.h:68:26:   required from here
[    8s] /usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/bits/stl_construct.h:75:13: error: invalid static_cast from type 'const std::pair<const char*, const char*>*' to type 'void*'
[    8s]      { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
[    8s]              ^~~~~~~~~~~~~~~~~~~~~~~
[    8s] src/CMakeFiles/hwcpipe.dir/build.make:89: recipe for target 'src/CMakeFiles/hwcpipe.dir/mali_counter.cpp.o' failed

May you consider to change the "const std::pair" to "std:pair"?

thx

**Comment by antonio-caggiano-arm** [comment]
Yes, indeed the standard (from C++11) requires `T` to be non-const for `vector<T>`.
Please, feel free to submit a pull request.

**Comment by AttilioProvenzano-ARM** [comment]
Fixed here: **https://github.com/ARM-software/HWCPipe/pull/10**
